# Generated by Django 3.0.3 on 2020-02-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=5000)),
                ('capacity', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_first_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('parent_phone_number', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('school_grade', models.IntegerField()),
                ('territory', models.IntegerField()),
                ('has_laptop', models.BooleanField(default=False)),
                ('birthday_date', models.CharField(max_length=50)),
                ('programming_familiar', models.TextField()),
                ('special_state', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('visit_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=1)),
                ('paid', models.IntegerField(default=0)),
                ('authority', models.CharField(default='none', max_length=200)),
                ('refid', models.CharField(default='none', max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registeration.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registeration.Person')),
            ],
        ),
    ]
